### ISSUE TITLE
Can't import this packange

### ISSUE THREAD

**Issue by krupagaliya** [derricw/asciisciit#1]
I m using Ubuntu  and in my virtual env I can't install this package although if I do `pip freeze`
 command asciisciit package showing in list
This error thrown by __init__.py , it can't find asciiart file
I checked the code but all seems ok, so can you please tell me what should I do ??

**Comment by derricw** [comment]
Are you trying to use this in python3? I think that is what is happening.  The package currently doesn't work with python3.  I have been meaning to update it but I have spent time on it in a while.

**Comment by derricw** [comment]
@krupagaliya I have pushed some updates to master (not on pypi yet) that should add python3 support.  let me know if that doesn't work!

**Comment by krupagaliya** [comment]
@derricw yes, after updates in master it works fine in python3
you did amazing work :+1: 
Thanks :)

**Comment by derricw** [comment]
@krupagaliya Great, and thank you! Glad you like it.
